### ISSUE TITLE
Using celltypes450 on subset of probes

### ISSUE THREAD

**Issue by turgeonmaxime** [brentp/celltypes450#2]
I tried using this package on a selected subset of probes. I made sure the probes contained in houseman-dmrs.txt were in my subset, but it still didn't work because
1) the first thing adjust.beta() checks is whether there is at least 2x10^5 probes with an ID starting with "cg", and I had about 1200 probes in total;
2) when it doesn't find enough probes, it uses the probe names contained in houseman-dmrs-locs.txt, of which I only had one.

I manage to make it work by adding ~2x10^5 extra probes to my subset, but I'm wondering if that's really the desired behaviour... adjusting only a subset of probes is most likely faster, which is why I didn't want to use the full set.

**Comment by brentp** [comment]
can you make a pull-request that just issues a warning and tries to do the right thing even if there are few probes?
