### ISSUE TITLE
MethylationEPIC

### ISSUE THREAD

**Issue by igordot** [brentp/celltypes450#5]
Does this work for the MethylationEPIC (850K) data? More than 90% of the 450K probes are covered and are supposed to generate comparable results. Thus, it should be possible, but I just wanted to confirm.

More importantly, since this was made before `minfi` `estimateCellCounts()`, is that the advised approach now?

**Comment by brentp** [comment]
I'm not sure if it will work and haven't tried. But sounds like if yo subset the probes to those in both 450K and the EPIC then it would work.
Yes, I would think `estimateCellCounts` would be preferable. But some people seem to have found this useful.
